# docker-compose.yml

services:
  db:
    image: postgres
    container_name: chapter_db_server
    restart: always
    
    ports:
      - "${DB_PORT}:${CONTAINER_PORT}" 
      
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
      
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: