/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Chapter } from './chapter';
import type { ChapterContent } from './chapterContent';
import type { LabelDataEntry } from './labelDataEntry';
import type { LabelGroupListEntry } from './labelGroupListEntry';
import type { Role } from './role';

/**
 * Pydantic schema for the data needed to edit a chapter.
 *
 * Attributes:
 *     chapter: Chapter being edited.
 *     chapter_content: ChapterContent being edited.
 *     label_groups: List of LabelGroups in this novel.
 *     labels: List of Labels in this chapter content.
 */
export interface EditChapterData {
  chapter: Chapter;
  chapterContent: ChapterContent;
  labelDataList: LabelDataEntry[];
  labelGroupList: LabelGroupListEntry[];
  role: Role;
}
