"""add glossary tables

Revision ID: 9148916294a0
Revises: 72ff918c4e2f
Create Date: 2026-04-01 22:41:00.670770+00:00

"""

# revision identifiers, used by Alembic.
revision = "9148916294a0"
down_revision = "72ff918c4e2f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
