/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  Schema as S
} from 'effect';


/**
 * @summary Read Autolabels
 */
export const ReadAutolabelsAutoLabelsGetQueryParams = S.Struct({
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "chapterIds": S.optional(S.Union(S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))), S.Null)),
  "start": S.optional(S.Union(S.Number, S.Null)),
  "end": S.optional(S.Union(S.Number, S.Null)),
  "modelNames": S.optional(S.Union(S.Array(S.Literal("cluener")), S.Null))
})

export const ReadAutolabelsAutoLabelsGetResponseItem = S.Struct({
  "autoLabelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "autoLabelLastJobId": S.String,
  "autoLabelMessage": S.optional(S.Union(S.String, S.Null)),
  "autoLabelModelName": S.Literal("cluener"),
  "autoLabelModelParams": S.Record({ key: S.String, value: S.Unknown }),
  "autoLabelStatus": S.Literal('failed', 'pending', 'processing', 'done').annotations({ description: 'Status for an autolabel in database. One of \'failed\', \'pending\', \'processing\', \'done\'' }),
  "chapterContentId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for auto-label metadata.\n\nAttributes:\n    auto_label_id: UUID identifier for this AutoLabel.\n    auto_label_model_name: Name of the model used to generate the auto labels.\n    auto_label_model_params: Parameters used for the model to generate the auto labels.\n    auto_label_status: Labeling progress for this autolabel.\n    auto_label_message: Details on status.\n    chapter_content_id: UUID of chapter content this AutoLabel is associated with.\n    auto_label_last_job_id: Job id of last job that was run on this AutoLabel.' })
export const ReadAutolabelsAutoLabelsGetResponse = S.Array(ReadAutolabelsAutoLabelsGetResponseItem)

/**
 * @summary Create Autolabels
 */
export const CreateAutolabelsAutoLabelsPostBody = S.Struct({
  "autoLabelModelName": S.Literal("cluener"),
  "autoLabelModelParams": S.Record({ key: S.String, value: S.Unknown }),
  "chapterIds": S.optional(S.Union(S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))), S.Null)),
  "end": S.optional(S.Union(S.Number, S.Null)),
  "isPublic": S.optional(S.Union(S.Boolean, S.Null)),
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "start": S.optional(S.Union(S.Number, S.Null))
}).annotations({ description: 'Pydantic schema for creating an auto-labeled data entry.\n\nAttributes:\n    novel_id: UUID of novel to create auto labels for.\n    auto_label_model_name: Name of the model used to generate the auto labels.\n    auto_label_model_params: Parameters used for the model to generate the auto labels.\n    chapter_ids: Optional parameter. Restrict to revisions with specific chapter UUIDs.\n    start: Optional parameter. Restrict to revisions with chapter num >= start.\n    end: Optional parameter. Restrict to revisions with chapter num < end.\n    is_public: Optional parameter. Restrict to revisions with this specific public flag.' })

export const CreateAutolabelsAutoLabelsPostResponseItem = S.Struct({
  "autoLabelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "autoLabelLastJobId": S.String,
  "autoLabelMessage": S.optional(S.Union(S.String, S.Null)),
  "autoLabelModelName": S.Literal("cluener"),
  "autoLabelModelParams": S.Record({ key: S.String, value: S.Unknown }),
  "autoLabelStatus": S.Literal('failed', 'pending', 'processing', 'done').annotations({ description: 'Status for an autolabel in database. One of \'failed\', \'pending\', \'processing\', \'done\'' }),
  "chapterContentId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for auto-label metadata.\n\nAttributes:\n    auto_label_id: UUID identifier for this AutoLabel.\n    auto_label_model_name: Name of the model used to generate the auto labels.\n    auto_label_model_params: Parameters used for the model to generate the auto labels.\n    auto_label_status: Labeling progress for this autolabel.\n    auto_label_message: Details on status.\n    chapter_content_id: UUID of chapter content this AutoLabel is associated with.\n    auto_label_last_job_id: Job id of last job that was run on this AutoLabel.' })
export const CreateAutolabelsAutoLabelsPostResponse = S.Array(CreateAutolabelsAutoLabelsPostResponseItem)

/**
 * Endpoint for retrieving autolabel from database.
 *
 * Args:
 *     auto_label_id: UUID for auto label.
 *     db: Database dependency.
 *     current_user: Current user dependency.
 * @summary Read Autolabel By Id
 */
export const ReadAutolabelByIdAutoLabelsAutoLabelIdGetParams = S.Struct({
  "autoLabelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const readAutolabelByIdAutoLabelsAutoLabelIdGetResponseAutoLabelDataOneItemLabelEndMin = 0;

export const readAutolabelByIdAutoLabelsAutoLabelIdGetResponseAutoLabelDataOneItemLabelEntityGroupOneMax = 64;

export const readAutolabelByIdAutoLabelsAutoLabelIdGetResponseAutoLabelDataOneItemLabelScoreMin = 0;
export const readAutolabelByIdAutoLabelsAutoLabelIdGetResponseAutoLabelDataOneItemLabelScoreMax = 1;

export const readAutolabelByIdAutoLabelsAutoLabelIdGetResponseAutoLabelDataOneItemLabelStartMin = 0;

export const readAutolabelByIdAutoLabelsAutoLabelIdGetResponseAutoLabelDataOneItemLabelWordMax = 128;



export const ReadAutolabelByIdAutoLabelsAutoLabelIdGetResponse = S.Struct({
  "autoLabelData": S.Union(S.Array(S.Struct({
  "labelDirty": S.Boolean,
  "labelEnd": S.Number.pipe(S.greaterThanOrEqualTo(readAutolabelByIdAutoLabelsAutoLabelIdGetResponseAutoLabelDataOneItemLabelEndMin)),
  "labelEntityGroup": S.Union(S.String.pipe(S.maxLength(readAutolabelByIdAutoLabelsAutoLabelIdGetResponseAutoLabelDataOneItemLabelEntityGroupOneMax)), S.Null),
  "labelScore": S.Number.pipe(S.greaterThanOrEqualTo(readAutolabelByIdAutoLabelsAutoLabelIdGetResponseAutoLabelDataOneItemLabelScoreMin), S.lessThanOrEqualTo(readAutolabelByIdAutoLabelsAutoLabelIdGetResponseAutoLabelDataOneItemLabelScoreMax)),
  "labelStart": S.Number.pipe(S.greaterThanOrEqualTo(readAutolabelByIdAutoLabelsAutoLabelIdGetResponseAutoLabelDataOneItemLabelStartMin)),
  "labelWord": S.String.pipe(S.maxLength(readAutolabelByIdAutoLabelsAutoLabelIdGetResponseAutoLabelDataOneItemLabelWordMax))
}).annotations({ description: 'Pydantic schema for a single label without a parent LabelData reference.\nUsed by autolabels and other contexts where labels exist independently of a LabelData.\n\nAttributes:\n    label_entity_group: Some arbitrary string denoting the entity group this label belongs to (e.g. PERSON, LOCATION, etc.).\n    label_score: Some float corresponding to how likely a label is to be correct. Used by label autogeneration modules (TBD).\n    label_word: Word that this label is labeling.\n    label_start: Start position of this label in text.\n    label_end: End position of this label in text.\n    label_dirty: Use TBD, most likely will be for score calculations in LabelData aggregate operations.\n\nNote:\n    label_start must be strictly less than label_end. Otherwise a ValueError will occur.\n    label_word must have length label_end - label_start. Otherwise a ValueError will occur.' })), S.Null),
  "autoLabelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "autoLabelLastJobId": S.String,
  "autoLabelMessage": S.optional(S.Union(S.String, S.Null)),
  "autoLabelModelName": S.Literal("cluener"),
  "autoLabelModelParams": S.Record({ key: S.String, value: S.Unknown }),
  "autoLabelStatus": S.Literal('failed', 'pending', 'processing', 'done').annotations({ description: 'Status for an autolabel in database. One of \'failed\', \'pending\', \'processing\', \'done\'' }),
  "chapterContentId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for an auto-labeled data entry.\n\nAttributes:\n    auto_label_id: UUID identifier for this AutoLabel.\n    auto_label_data: Dictionary containing the auto-labeled data.\n    auto_label_model_name: Name of the model used to generate the auto labels.\n    auto_label_model_params: Parameters used for the model to generate the auto labels.\n    auto_label_status: Labeling progress for this autolabel.\n    auto_label_message: Details on status.\n    chapter_content_id: UUID of chapter content this AutoLabel is associated with.\n    auto_label_last_job_id: Job id of last job that was run on this AutoLabel.' })

/**
 * @summary Get Cached Result
 */
export const GetCachedResultCachedCachedIdGetParams = S.Struct({
  "cachedId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const GetCachedResultCachedCachedIdGetResponse = S.Struct({
  "error": S.Union(S.Struct({
  "cacheConflict": S.Boolean,
  "detail": S.String
}), S.Null),
  "response": S.Union(S.Record({ key: S.String, value: S.Unknown }), S.Null),
  "status": S.Literal('pending', 'success', 'failure'),
  "status_code": S.Union(S.Number, S.Null)
})

/**
 * Endpoint for retrieving a specific version of chapter content by its id.
 *
 * Raises:
 *     404: Chapter content not found (or insufficient permissions).
 * @summary Read Chapter Content By Id
 */
export const ReadChapterContentByIdChapterContentsChapterContentIdGetParams = S.Struct({
  "chapterContentId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const ReadChapterContentByIdChapterContentsChapterContentIdGetResponse = S.Struct({
  "chapterContentId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "chapterContentText": S.String,
  "chapterContentVersion": S.Number
}).annotations({ description: 'Pydantic schema for the text content of a chapter.\n\nAttributes:\n    chapter_content_text: The full text content of the chapter.\n    chapter_content_version: The version number of the text content, used for optimistic concurrency control when updating text.\n    chapter_content_id: The UUID of the text content, used for optimistic concurrency control when updating text.' })

/**
 * Endpoint for retrieving chapters by novel_id.
 *
 * Raises:
 *     404: Novel not found (or insufficient permissions).
 * @summary Read Chapters By Novel
 */
export const ReadChaptersByNovelChaptersGetQueryParams = S.Struct({
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "start": S.optional(S.Union(S.Number, S.Null)),
  "end": S.optional(S.Union(S.Number, S.Null))
})

export const ReadChaptersByNovelChaptersGetResponseItem = S.Struct({
  "chapterId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "chapterIsPublic": S.Boolean,
  "chapterNum": S.Number,
  "chapterTitle": S.String,
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for chapter metadata. Represents a single \"chapter\" entry, which groups all its revisions.\n\nAttributes:\n    chapter_id: UUID primary key identifier.\n    chapter_num: The chapter number.\n    novel_id: UUID foreign key to the novel this chapter belongs to.' })
export const ReadChaptersByNovelChaptersGetResponse = S.Array(ReadChaptersByNovelChaptersGetResponseItem)

/**
 * Delete a chapter from the database.
 *
 * Raises:
 *     404: Chapter not found.
 *     401: Insufficient permissions.
 *     500: Delete failed for other reasons.
 * @summary Delete Chapter
 */
export const DeleteChapterChaptersChapterIdDeleteParams = S.Struct({
  "chapterId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const DeleteChapterChaptersChapterIdDeleteResponse = S.Struct({
  "detail": S.optional(S.Union(S.String, S.Null)),
  "status": S.Literal('success', 'fail')
}).annotations({ description: 'Pydantic model to signal return status of operation.\n\nAttributes:\n    status: One of \"success\", \"fail\".\n    detail: Details on operation.\n\nNotes:\n    Unless under exceptional circumstances, should not return fail and just raise an exception.' })

/**
 * Endpoint for retrieving chapter by id.
 *
 * Raises:
 *     404: Chapter not found (or insufficient permissions).
 * @summary Read Chapter By Id
 */
export const ReadChapterByIdChaptersChapterIdGetParams = S.Struct({
  "chapterId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const ReadChapterByIdChaptersChapterIdGetResponse = S.Struct({
  "chapterId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "chapterIsPublic": S.Boolean,
  "chapterNum": S.Number,
  "chapterTitle": S.String,
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for chapter metadata. Represents a single \"chapter\" entry, which groups all its revisions.\n\nAttributes:\n    chapter_id: UUID primary key identifier.\n    chapter_num: The chapter number.\n    novel_id: UUID foreign key to the novel this chapter belongs to.' })

/**
 * Update chapter metadata.
 *
 * Raises:
 *     404: Chapter not found.
 *     401: Insufficient permissions.
 *     400: Field in request too long.
 * @summary Update Chapter
 */
export const UpdateChapterChaptersChapterIdPatchParams = S.Struct({
  "chapterId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const UpdateChapterChaptersChapterIdPatchBody = S.Struct({
  "chapterTitle": S.String
}).annotations({ description: 'Pydantic schema to validate data for updating chapter metadata.\n\nAttributes:\n    chapter_title: The new title for the chapter.' })

export const UpdateChapterChaptersChapterIdPatchResponse = S.Struct({
  "chapterId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "chapterIsPublic": S.Boolean,
  "chapterNum": S.Number,
  "chapterTitle": S.String,
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for chapter metadata. Represents a single \"chapter\" entry, which groups all its revisions.\n\nAttributes:\n    chapter_id: UUID primary key identifier.\n    chapter_num: The chapter number.\n    novel_id: UUID foreign key to the novel this chapter belongs to.' })

/**
 * Endpoint for retrieving the most recent content of a chapter.
 *
 * Raises:
 *     404: Chapter not found, or chapter has no content.
 * @summary Read Chapter Content
 */
export const ReadChapterContentChaptersChapterIdContentGetParams = S.Struct({
  "chapterId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const ReadChapterContentChaptersChapterIdContentGetResponse = S.Struct({
  "chapterContentId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "chapterContentText": S.String,
  "chapterContentVersion": S.Number
}).annotations({ description: 'Pydantic schema for the text content of a chapter.\n\nAttributes:\n    chapter_content_text: The full text content of the chapter.\n    chapter_content_version: The version number of the text content, used for optimistic concurrency control when updating text.\n    chapter_content_id: The UUID of the text content, used for optimistic concurrency control when updating text.' })

/**
 * Apply text operations to the most recent content of a chapter. Uses optimistic concurrency
 * via chapter_content_id -- if the content has been modified since the client last fetched it,
 * a 409 is returned.
 *
 * Raises:
 *     404: Chapter content not found.
 *     409: Chapter content is outdated (someone else modified it).
 *     401: Insufficient permissions to modify this chapter.
 * @summary Update Chapter Content
 */
export const UpdateChapterContentChaptersChapterIdContentPatchParams = S.Struct({
  "chapterId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const UpdateChapterContentChaptersChapterIdContentPatchQueryParams = S.Struct({
  "requestKey": S.optional(S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null))
})

export const UpdateChapterContentChaptersChapterIdContentPatchBody = S.Struct({
  "chapterContentId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "textOps": S.Array(S.Struct({
  "op": S.Literal('insert', 'delete'),
  "start": S.Number,
  "text": S.String
}).annotations({ description: 'Pydantic schema to update text content of a chapter.\n\nAttributes:\n    op: The text operation, either \"insert\" or \"delete\".\n    start: The starting index in the text content where the operation should be applied.\n    text: The text to insert (for insert operations) or the text to delete (for delete operations).' }))
}).annotations({ description: 'Pydantic schema to validate data for updating the text content of a chapter. The chapter_id is expected to be passed via the URL path.\n\nAttributes:\n    text_ops: A list of text operations (insertions or deletions) to apply to the existing text content.\n    chapter_content_id: The UUID of the text content, used for optimistic concurrency control when updating text.' })

export const UpdateChapterContentChaptersChapterIdContentPatchResponse = S.Struct({
  "chapterContentId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "chapterContentVersion": S.Number,
  "labelDataIdMap": S.Record({ key: S.String, value: S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)) })
}).annotations({ description: 'Pydantic schema for the response after modifying chapter content.\n\nAttributes:\n    chapter_content_version: The new version number of the text content after applying the modifications.\n    chapter_content_id: The UUID of the text content that was modified.\n    label_data_id_map: A mapping from label data IDs before the text modification to label data IDs after the text modification' })

/**
 * Check whether a chapter_content_id is the latest version for a chapter.
 *
 * Raises:
 *     404: Chapter content not found (or insufficient read permissions).
 *     409: Chapter content is outdated.
 * @summary Read Chapter Content Status
 */
export const ReadChapterContentStatusChaptersChapterIdContentStatusChapterContentIdGetParams = S.Struct({
  "chapterId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "chapterContentId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const ReadChapterContentStatusChaptersChapterIdContentStatusChapterContentIdGetResponse = S.Struct({
  "detail": S.optional(S.Union(S.String, S.Null)),
  "status": S.Literal('success', 'fail')
}).annotations({ description: 'Pydantic model to signal return status of operation.\n\nAttributes:\n    status: One of \"success\", \"fail\".\n    detail: Details on operation.\n\nNotes:\n    Unless under exceptional circumstances, should not return fail and just raise an exception.' })

/**
 * Endpoint for retrieving all content version metadata for a chapter.
 * Returns an empty list if the chapter has no content versions or doesn't exist.
 * @summary Read Chapter Content Versions
 */
export const ReadChapterContentVersionsChaptersChapterIdContentVersionsGetParams = S.Struct({
  "chapterId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const ReadChapterContentVersionsChaptersChapterIdContentVersionsGetResponseItem = S.Struct({
  "chapterContentId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "chapterContentVersion": S.Number
}).annotations({ description: 'Metadata for a ChapterContent.\n\nAttributes:\n    chapter_content_version: The version number of the text content, used for optimistic concurrency control when updating text.\n    chapter_content_id: The UUID of the text content, used for optimistic concurrency control when updating text.' })
export const ReadChapterContentVersionsChaptersChapterIdContentVersionsGetResponse = S.Array(ReadChapterContentVersionsChaptersChapterIdContentVersionsGetResponseItem)

/**
 * Publish a chapter (make it public).
 *
 * Raises:
 *     404: Chapter not found.
 *     401: Insufficient permissions.
 * @summary Action Publish Chapter
 */
export const ActionPublishChapterChaptersChapterIdPublishPostParams = S.Struct({
  "chapterId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const ActionPublishChapterChaptersChapterIdPublishPostResponse = S.Struct({
  "chapterId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "chapterIsPublic": S.Boolean,
  "chapterNum": S.Number,
  "chapterTitle": S.String,
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for chapter metadata. Represents a single \"chapter\" entry, which groups all its revisions.\n\nAttributes:\n    chapter_id: UUID primary key identifier.\n    chapter_num: The chapter number.\n    novel_id: UUID foreign key to the novel this chapter belongs to.' })

/**
 * Gets all data associated with a chapter required for editing.
 *
 * Args:
 *     chapter_id: Chapter id of requested chapter
 *     novel_id: Novel id of requested chapter
 *
 * Raises:
 *     404: Chapter not found (or insufficient permissions).
 * @summary Read Edit Chapter Data
 */
export const ReadEditChapterDataEditChapterDataChapterIdGetParams = S.Struct({
  "chapterId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const readEditChapterDataEditChapterDataChapterIdGetQueryLabelGroupsNumMax = 20;



export const ReadEditChapterDataEditChapterDataChapterIdGetQueryParams = S.Struct({
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "labelGroupsNum": S.Number.pipe(S.greaterThanOrEqualTo(1), S.lessThanOrEqualTo(readEditChapterDataEditChapterDataChapterIdGetQueryLabelGroupsNumMax)),
  "subjectId": S.optional(S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null))
})

export const readEditChapterDataEditChapterDataChapterIdGetResponseLabelDataListItemLabelsItemLabelEndMin = 0;

export const readEditChapterDataEditChapterDataChapterIdGetResponseLabelDataListItemLabelsItemLabelEntityGroupOneMax = 64;

export const readEditChapterDataEditChapterDataChapterIdGetResponseLabelDataListItemLabelsItemLabelScoreMin = 0;
export const readEditChapterDataEditChapterDataChapterIdGetResponseLabelDataListItemLabelsItemLabelScoreMax = 1;

export const readEditChapterDataEditChapterDataChapterIdGetResponseLabelDataListItemLabelsItemLabelStartMin = 0;

export const readEditChapterDataEditChapterDataChapterIdGetResponseLabelDataListItemLabelsItemLabelWordMax = 128;

export const readEditChapterDataEditChapterDataChapterIdGetResponseLabelGroupListItemLabelGroupLabelGroupNameMax = 31;



export const ReadEditChapterDataEditChapterDataChapterIdGetResponse = S.Struct({
  "chapter": S.Struct({
  "chapterId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "chapterIsPublic": S.Boolean,
  "chapterNum": S.Number,
  "chapterTitle": S.String,
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for chapter metadata. Represents a single \"chapter\" entry, which groups all its revisions.\n\nAttributes:\n    chapter_id: UUID primary key identifier.\n    chapter_num: The chapter number.\n    novel_id: UUID foreign key to the novel this chapter belongs to.' }),
  "chapterContent": S.Struct({
  "chapterContentId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "chapterContentText": S.String,
  "chapterContentVersion": S.Number
}).annotations({ description: 'Pydantic schema for the text content of a chapter.\n\nAttributes:\n    chapter_content_text: The full text content of the chapter.\n    chapter_content_version: The version number of the text content, used for optimistic concurrency control when updating text.\n    chapter_content_id: The UUID of the text content, used for optimistic concurrency control when updating text.' }),
  "labelDataList": S.Array(S.Struct({
  "labelDataId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "labels": S.Array(S.Struct({
  "labelDataId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "labelDirty": S.Boolean,
  "labelEnd": S.Number.pipe(S.greaterThanOrEqualTo(readEditChapterDataEditChapterDataChapterIdGetResponseLabelDataListItemLabelsItemLabelEndMin)),
  "labelEntityGroup": S.Union(S.String.pipe(S.maxLength(readEditChapterDataEditChapterDataChapterIdGetResponseLabelDataListItemLabelsItemLabelEntityGroupOneMax)), S.Null),
  "labelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "labelScore": S.Number.pipe(S.greaterThanOrEqualTo(readEditChapterDataEditChapterDataChapterIdGetResponseLabelDataListItemLabelsItemLabelScoreMin), S.lessThanOrEqualTo(readEditChapterDataEditChapterDataChapterIdGetResponseLabelDataListItemLabelsItemLabelScoreMax)),
  "labelStart": S.Number.pipe(S.greaterThanOrEqualTo(readEditChapterDataEditChapterDataChapterIdGetResponseLabelDataListItemLabelsItemLabelStartMin)),
  "labelWord": S.String.pipe(S.maxLength(readEditChapterDataEditChapterDataChapterIdGetResponseLabelDataListItemLabelsItemLabelWordMax))
}).annotations({ description: 'Pydantic schema for a label that belongs to a LabelData.\nExtends LabelBase with a label_data_id foreign key and label_id pkey.' }))
})),
  "labelGroupList": S.Array(S.Struct({
  "labelData": S.Union(S.Struct({
  "chapterContentId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "labelDataId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "labelGroupId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for a list of labels in some text.\n\nAttributes:\n    label_data_id: UUID identifier for this LabelData.\n    label_group_id: UUID of label group this LabelData belongs to.\n    chapter_content_id: UUID of chapter content this LabelData is labelling.' }), S.Null),
  "labelGroup": S.Struct({
  "labelGroupId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "labelGroupName": S.String.pipe(S.maxLength(readEditChapterDataEditChapterDataChapterIdGetResponseLabelGroupListItemLabelGroupLabelGroupNameMax)),
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for a label group.\n\nAttributes:\n    label_group_id: UUID identifier for this label group.\n    label_group_name: Name of this label group.\n    novel_id: UUID of novel this label group belongs to.' }),
  "role": S.Literal('owner', 'viewer', 'editor')
})),
  "role": S.Literal('owner', 'viewer', 'editor')
}).annotations({ description: 'Pydantic schema for the data needed to edit a chapter.\n\nAttributes:\n    chapter: Chapter being edited.\n    chapter_content: ChapterContent being edited.\n    label_groups: List of LabelGroups in this novel.\n    labels: List of Labels in this chapter content.' })

/**
 * Retrieves the schemas for all registered filters, including the instance, context, and options schemas for each filter.
 *
 * Returns:
 *     A dictionary mapping filter names to their schema information.
 * @summary Read Filter Schemas
 */
export const ReadFilterSchemasFiltersSchemasGetResponse = S.Record({ key: S.String, value: S.Struct({
  "apply_filter_options_schema": S.Record({ key: S.String, value: S.Unknown }),
  "context_schema": S.Record({ key: S.String, value: S.Unknown }),
  "decide_instances_options_schema": S.Record({ key: S.String, value: S.Unknown }),
  "description": S.String,
  "flag_instances_options_schema": S.Record({ key: S.String, value: S.Unknown }),
  "get_contexts_options_schema": S.Record({ key: S.String, value: S.Unknown }),
  "instance_schema": S.Record({ key: S.String, value: S.Unknown }),
  "supports_apply": S.Boolean,
  "supports_decide": S.Boolean
}) })

/**
 * Applies a filter to a label group for a list of instances using specified options.
 *
 * Args:
 *     filter_name: The name of the filter to apply.
 *     body: An InstanceOptions object containing the list of instances and the options for applying the filter. Each instance will be validated against the filter's instance schema, and the options will be validated against the filter's apply filter options schema.
 *     db: Database session for any necessary database access during filter application.
 *     current_user: The user making the request, which may be relevant for certain filters.
 * @summary Apply Filter
 */
export const ApplyFilterFiltersFilterNameApplyPostParams = S.Struct({
  "filterName": S.String
})

export const ApplyFilterFiltersFilterNameApplyPostBody = S.Struct({
  "instances": S.Array(S.Unknown),
  "options": S.Record({ key: S.String, value: S.Unknown })
})

/**
 * Decides whether instances pass a filter in given contexts using specified options.
 *
 * Args:
 *     filter_name: The name of the filter to use.
 *     body: An InstanceContextOptions object containing the list of instance-context pairs and the options for deciding instances. Each instance and context will be validated against the filter's schemas.
 *     db: Database session for any necessary database access during the decision process.
 *     current_user: The user making the request, which may be relevant for certain filters.
 * @summary Read Decisions
 */
export const ReadDecisionsFiltersFilterNameDecideInstancesPostParams = S.Struct({
  "filterName": S.String
})

export const ReadDecisionsFiltersFilterNameDecideInstancesPostBody = S.Struct({
  "instanceContexts": S.Array(S.Tuple(S.Unknown, S.Unknown)),
  "options": S.Record({ key: S.String, value: S.Unknown })
})

export const ReadDecisionsFiltersFilterNameDecideInstancesPostResponseItem = S.Boolean
export const ReadDecisionsFiltersFilterNameDecideInstancesPostResponse = S.Array(ReadDecisionsFiltersFilterNameDecideInstancesPostResponseItem)

/**
 * Flags instances using a specified filter and options.
 *
 * Args:
 *     filter_name: The name of the filter to use.
 *     options: The options for flagging instances, which will be validated against the filter's schema.
 *     db: Database session for any necessary database access during filtering.
 *     current_user: The user making the request, which may be relevant for certain filters.
 * @summary Read Flagged Instances
 */
export const ReadFlaggedInstancesFiltersFilterNameFlagInstancesPostParams = S.Struct({
  "filterName": S.String
})

export const ReadFlaggedInstancesFiltersFilterNameFlagInstancesPostBody = S.Record({ key: S.String, value: S.Unknown })

export const ReadFlaggedInstancesFiltersFilterNameFlagInstancesPostResponseItem = S.Unknown
export const ReadFlaggedInstancesFiltersFilterNameFlagInstancesPostResponse = S.Array(ReadFlaggedInstancesFiltersFilterNameFlagInstancesPostResponseItem)

/**
 * Retrieves contexts for a list of instances using a specified filter and options.
 *
 * Args:
 *     filter_name: The name of the filter to use.
 *     instances: The list of instances to retrieve contexts for. Each instance will be validated against the filter's instance schema.
 *     options: The options for retrieving contexts, which will be validated against the filter's schema.
 *     db: Database session for any necessary database access during context retrieval.
 *     current_user: The user making the request, which may be relevant for certain filters.
 * @summary Read Contexts
 */
export const ReadContextsFiltersFilterNameGetContextsPostParams = S.Struct({
  "filterName": S.String
})

export const ReadContextsFiltersFilterNameGetContextsPostBody = S.Struct({
  "instances": S.Array(S.Unknown),
  "options": S.Record({ key: S.String, value: S.Unknown })
})

export const ReadContextsFiltersFilterNameGetContextsPostResponseItem = S.Unknown
export const ReadContextsFiltersFilterNameGetContextsPostResponse = S.Array(ReadContextsFiltersFilterNameGetContextsPostResponseItem)

/**
 * Gets all label datas in a label group, optionally filtered by chapter range.
 * @summary Read Label Datas By Group Chapters
 */
export const ReadLabelDatasByGroupChaptersLabelDatasGetQueryParams = S.Struct({
  "labelGroupId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "start": S.optional(S.Union(S.Number, S.Null)),
  "end": S.optional(S.Union(S.Number, S.Null))
})

export const ReadLabelDatasByGroupChaptersLabelDatasGetResponseItem = S.Struct({
  "chapterContentId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "labelDataId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "labelGroupId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for a list of labels in some text.\n\nAttributes:\n    label_data_id: UUID identifier for this LabelData.\n    label_group_id: UUID of label group this LabelData belongs to.\n    chapter_content_id: UUID of chapter content this LabelData is labelling.' })
export const ReadLabelDatasByGroupChaptersLabelDatasGetResponse = S.Array(ReadLabelDatasByGroupChaptersLabelDatasGetResponseItem)

/**
 * Gets a label data by id.
 *
 * Raises:
 *     404: Label data not found (or insufficient permissions).
 * @summary Read Label Data
 */
export const ReadLabelDataLabelDatasLabelDataIdGetParams = S.Struct({
  "labelDataId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const ReadLabelDataLabelDatasLabelDataIdGetResponse = S.Struct({
  "chapterContentId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "labelDataId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "labelGroupId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for a list of labels in some text.\n\nAttributes:\n    label_data_id: UUID identifier for this LabelData.\n    label_group_id: UUID of label group this LabelData belongs to.\n    chapter_content_id: UUID of chapter content this LabelData is labelling.' })

/**
 * Applies a stream of edit operations to labels.
 *
 * Raises:
 *     404: Label data or its underlying revision text not found, or target label does not exist.
 *     409: Word mismatch or label overlap detected.
 *     400: Operation positions out of bounds or invalid operation.
 * @summary Update Label Data Stream
 */
export const UpdateLabelDataStreamLabelDatasLabelDataIdPatchParams = S.Struct({
  "labelDataId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const UpdateLabelDataStreamLabelDatasLabelDataIdPatchQueryParams = S.Struct({
  "requestKey": S.optional(S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null))
})

export const updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemOneDirtyDefault = true;
export const updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemOneEndPosMin = 0;

export const updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemOneEntityGroupOneMax = 64;

export const updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemOneScoreDefault = 1;
export const updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemOneScoreMin = 0;
export const updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemOneScoreMax = 1;

export const updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemOneStartPosMin = 0;

export const updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemOneWordMax = 128;

export const updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemTwoEndPosMin = 0;

export const updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemTwoStartPosMin = 0;

export const updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemTwoWordMax = 128;

export const updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemThreeEndPosMin = 0;

export const updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemThreeEntityGroupOneMax = 64;

export const updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemThreeNewEndPosOneMin = 0;

export const updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemThreeNewStartPosOneMin = 0;

export const updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemThreeNewWordOneMax = 128;

export const updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemThreeScoreOneMin = 0;
export const updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemThreeScoreOneMax = 1;

export const updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemThreeStartPosMin = 0;

export const updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemThreeWordMax = 128;



export const UpdateLabelDataStreamLabelDatasLabelDataIdPatchBody = S.Struct({
  "ops": S.Array(S.Union(S.Struct({
  "dirty": S.optionalWith(S.Boolean, { default: () => updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemOneDirtyDefault }),
  "endPos": S.Number.pipe(S.greaterThanOrEqualTo(updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemOneEndPosMin)),
  "entityGroup": S.optional(S.Union(S.String.pipe(S.maxLength(updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemOneEntityGroupOneMax)), S.Null)),
  "op": S.Literal("add"),
  "score": S.optionalWith(S.Number.pipe(S.greaterThanOrEqualTo(updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemOneScoreMin), S.lessThanOrEqualTo(updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemOneScoreMax)), { default: () => updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemOneScoreDefault }),
  "startPos": S.Number.pipe(S.greaterThanOrEqualTo(updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemOneStartPosMin)),
  "word": S.String.pipe(S.maxLength(updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemOneWordMax))
}).annotations({ description: 'Pydantic schema for a label add operation. Inherits all attributes from LabelOpBase.\n\nAttributes:\n    op: The string literal \'add\'.\n    dirty: Boolean whether to mark the label as dirty.\n    entity_group: String representing what entity group this label belongs to. If none, then set a default value.\n    score: Float score between 0.0 and 1.0 representing how likely this label is to be an entity.' }), S.Struct({
  "endPos": S.Number.pipe(S.greaterThanOrEqualTo(updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemTwoEndPosMin)),
  "op": S.Literal("delete"),
  "startPos": S.Number.pipe(S.greaterThanOrEqualTo(updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemTwoStartPosMin)),
  "word": S.String.pipe(S.maxLength(updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemTwoWordMax))
}).annotations({ description: 'Pydantic schema for a label delete operation. Inherits all attributes from LabelOpBase.\n\nAttributes:\n    op: The string literal \'delete\'.' }), S.Struct({
  "dirty": S.optional(S.Union(S.Boolean, S.Null)),
  "endPos": S.Number.pipe(S.greaterThanOrEqualTo(updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemThreeEndPosMin)),
  "entityGroup": S.optional(S.Union(S.String.pipe(S.maxLength(updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemThreeEntityGroupOneMax)), S.Null)),
  "newEndPos": S.optional(S.Union(S.Number.pipe(S.greaterThanOrEqualTo(updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemThreeNewEndPosOneMin)), S.Null)),
  "newStartPos": S.optional(S.Union(S.Number.pipe(S.greaterThanOrEqualTo(updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemThreeNewStartPosOneMin)), S.Null)),
  "newWord": S.optional(S.Union(S.String.pipe(S.maxLength(updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemThreeNewWordOneMax)), S.Null)),
  "op": S.Literal("update"),
  "score": S.optional(S.Union(S.Number.pipe(S.greaterThanOrEqualTo(updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemThreeScoreOneMin), S.lessThanOrEqualTo(updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemThreeScoreOneMax)), S.Null)),
  "startPos": S.Number.pipe(S.greaterThanOrEqualTo(updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemThreeStartPosMin)),
  "word": S.String.pipe(S.maxLength(updateLabelDataStreamLabelDatasLabelDataIdPatchBodyOpsItemThreeWordMax))
}).annotations({ description: 'Pydantic schema for a label update operation. Inherits all attributes from LabelOpBase.\n\nAttributes:\n    op: The string literal \'update\'.\n    new_start_pos: Optional parameter. The new start position of the label.\n    new_end_pos: Optional parameter. The new end position of the label.\n    new_word: Optional parameter. The new word the label is labelling. Must satisfy `new_word == chapter_text[new_start_pos : new_end_pos]`.\n    dirty: Optional parameter. Value to change the current label\'s dirty value to.\n    entity_group: Optional parameter. New entity group for this label.\n    score: Optional parameter. New score for the entity.' })))
}).annotations({ description: 'Pydantic schema for a buffered stream of label operations.\n\nAttributes:\n    ops: A list of label operations.' })

/**
 * Get the specific list of labels inside a label data entry.
 * @summary Read Labels By Label Data
 */
export const ReadLabelsByLabelDataLabelDatasLabelDataIdLabelsGetParams = S.Struct({
  "labelDataId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const readLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponseLabelEndMin = 0;

export const readLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponseLabelEntityGroupOneMax = 64;

export const readLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponseLabelScoreMin = 0;
export const readLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponseLabelScoreMax = 1;

export const readLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponseLabelStartMin = 0;

export const readLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponseLabelWordMax = 128;



export const ReadLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponseItem = S.Struct({
  "labelDataId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "labelDirty": S.Boolean,
  "labelEnd": S.Number.pipe(S.greaterThanOrEqualTo(readLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponseLabelEndMin)),
  "labelEntityGroup": S.Union(S.String.pipe(S.maxLength(readLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponseLabelEntityGroupOneMax)), S.Null),
  "labelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "labelScore": S.Number.pipe(S.greaterThanOrEqualTo(readLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponseLabelScoreMin), S.lessThanOrEqualTo(readLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponseLabelScoreMax)),
  "labelStart": S.Number.pipe(S.greaterThanOrEqualTo(readLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponseLabelStartMin)),
  "labelWord": S.String.pipe(S.maxLength(readLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponseLabelWordMax))
}).annotations({ description: 'Pydantic schema for a label that belongs to a LabelData.\nExtends LabelBase with a label_data_id foreign key and label_id pkey.' })
export const ReadLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponse = S.Array(ReadLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponseItem)

/**
 * Gets all label groups of the current user for a novel.
 * @summary Read Label Groups
 */
export const ReadLabelGroupsLabelGroupsGetQueryParams = S.Struct({
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const readLabelGroupsLabelGroupsGetResponseLabelGroupNameMax = 31;



export const ReadLabelGroupsLabelGroupsGetResponseItem = S.Struct({
  "labelGroupId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "labelGroupName": S.String.pipe(S.maxLength(readLabelGroupsLabelGroupsGetResponseLabelGroupNameMax)),
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for a label group.\n\nAttributes:\n    label_group_id: UUID identifier for this label group.\n    label_group_name: Name of this label group.\n    novel_id: UUID of novel this label group belongs to.' })
export const ReadLabelGroupsLabelGroupsGetResponse = S.Array(ReadLabelGroupsLabelGroupsGetResponseItem)

/**
 * Creates a new label group.
 *
 * Raises:
 *     404: Novel not found.
 *     400: Label group name is too long.
 * @summary Create Label Group
 */
export const CreateLabelGroupLabelGroupsPostQueryParams = S.Struct({
  "requestKey": S.optional(S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null))
})

export const createLabelGroupLabelGroupsPostBodyLabelGroupNameMax = 31;



export const CreateLabelGroupLabelGroupsPostBody = S.Struct({
  "labelGroupName": S.String.pipe(S.maxLength(createLabelGroupLabelGroupsPostBodyLabelGroupNameMax)),
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for validating forms for creating a label group.\n\nAttributes:\n    label_group_name: Name of label group to create.\n    novel_id: UUID of novel this label group belongs to.' })

export const createLabelGroupLabelGroupsPostResponseLabelGroupNameMax = 31;



export const CreateLabelGroupLabelGroupsPostResponse = S.Struct({
  "labelGroupId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "labelGroupName": S.String.pipe(S.maxLength(createLabelGroupLabelGroupsPostResponseLabelGroupNameMax)),
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for a label group.\n\nAttributes:\n    label_group_id: UUID identifier for this label group.\n    label_group_name: Name of this label group.\n    novel_id: UUID of novel this label group belongs to.' })

/**
 * Gets a label group by id.
 *
 * Raises:
 *     404: Label group not found (or insufficient permissions).
 * @summary Read Label Group
 */
export const ReadLabelGroupLabelGroupsLabelGroupIdGetParams = S.Struct({
  "labelGroupId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const readLabelGroupLabelGroupsLabelGroupIdGetResponseLabelGroupNameMax = 31;



export const ReadLabelGroupLabelGroupsLabelGroupIdGetResponse = S.Struct({
  "labelGroupId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "labelGroupName": S.String.pipe(S.maxLength(readLabelGroupLabelGroupsLabelGroupIdGetResponseLabelGroupNameMax)),
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for a label group.\n\nAttributes:\n    label_group_id: UUID identifier for this label group.\n    label_group_name: Name of this label group.\n    novel_id: UUID of novel this label group belongs to.' })

/**
 * Updates a label group (e.g. rename).
 *
 * Raises:
 *     404: Label group not found.
 *     400: Label group name is too long.
 * @summary Update Label Group
 */
export const UpdateLabelGroupLabelGroupsLabelGroupIdPatchParams = S.Struct({
  "labelGroupId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const updateLabelGroupLabelGroupsLabelGroupIdPatchBodyLabelGroupNameMax = 31;



export const UpdateLabelGroupLabelGroupsLabelGroupIdPatchBody = S.Struct({
  "labelGroupName": S.String.pipe(S.maxLength(updateLabelGroupLabelGroupsLabelGroupIdPatchBodyLabelGroupNameMax))
}).annotations({ description: 'Pydantic schema for validating forms for updating a label group.\n\nAttributes:\n    label_group_name: New name of label group.' })

export const updateLabelGroupLabelGroupsLabelGroupIdPatchResponseLabelGroupNameMax = 31;



export const UpdateLabelGroupLabelGroupsLabelGroupIdPatchResponse = S.Struct({
  "labelGroupId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "labelGroupName": S.String.pipe(S.maxLength(updateLabelGroupLabelGroupsLabelGroupIdPatchResponseLabelGroupNameMax)),
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for a label group.\n\nAttributes:\n    label_group_id: UUID identifier for this label group.\n    label_group_name: Name of this label group.\n    novel_id: UUID of novel this label group belongs to.' })

/**
 * Get the list of contributors for a label group.
 * @summary Read Label Contributors
 */
export const ReadLabelContributorsLabelGroupsLabelGroupIdContributorsGetParams = S.Struct({
  "labelGroupId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const ReadLabelContributorsLabelGroupsLabelGroupIdContributorsGetResponseItem = S.Struct({
  "labelContributorRole": S.Literal('owner', 'viewer', 'editor'),
  "labelGroupId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "userId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for a label contributor, which can be either a user or an autolabel model.\n\nAttributes:\n    label_contributor_role: Role of the contributor, either a user or an autolabel model.\n    label_group_id: UUID of label group this contributor belongs to.\n    user_id: UUID of user' })
export const ReadLabelContributorsLabelGroupsLabelGroupIdContributorsGetResponse = S.Array(ReadLabelContributorsLabelGroupsLabelGroupIdContributorsGetResponseItem)

/**
 * Creates a label data entry for a revision text in a label group.
 *
 * Raises:
 *     404: Label group or revision text not found.
 *     409: Label data for this revision text already exists in this group.
 * @summary Create Label Data
 */
export const CreateLabelDataLabelGroupsLabelGroupIdLabelDatasPostParams = S.Struct({
  "labelGroupId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const CreateLabelDataLabelGroupsLabelGroupIdLabelDatasPostQueryParams = S.Struct({
  "requestKey": S.optional(S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null))
})

export const CreateLabelDataLabelGroupsLabelGroupIdLabelDatasPostBody = S.Struct({
  "chapterContentId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for validating create requests for label data.\n\nAttributes:\n    chapter_content_id: UUID of chapter content being labelled.' })

export const CreateLabelDataLabelGroupsLabelGroupIdLabelDatasPostResponse = S.Struct({
  "chapterContentId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "labelDataId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "labelGroupId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for a list of labels in some text.\n\nAttributes:\n    label_data_id: UUID identifier for this LabelData.\n    label_group_id: UUID of label group this LabelData belongs to.\n    chapter_content_id: UUID of chapter content this LabelData is labelling.' })

/**
 * Creates label datas and populates labels from autolabel results.
 * @summary Create Label Datas By Auto Labels
 */
export const CreateLabelDatasByAutoLabelsLabelGroupsLabelGroupIdLabelDatasAutoLabelsPostParams = S.Struct({
  "labelGroupId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const CreateLabelDatasByAutoLabelsLabelGroupsLabelGroupIdLabelDatasAutoLabelsPostBody = S.Struct({
  "chapterIds": S.optional(S.Union(S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))), S.Null)),
  "end": S.optional(S.Union(S.Number, S.Null)),
  "modelName": S.Literal("cluener"),
  "modelParams": S.Record({ key: S.String, value: S.Unknown }),
  "start": S.optional(S.Union(S.Number, S.Null))
}).annotations({ description: 'Pydantic schema to specifiy a set of AutoLabels to be moved to LabelDatas.\n\nAttributes:\n    model_name: Name of NER model that performed the autolabeling.\n    model_params: Parameters of model used.\n    chapter_ids: Optional filter on what chapters to include.\n    start: Optional filter on the least chapter number to include.\n    end: Optional filter on the greatest chapter number to include.' })

export const CreateLabelDatasByAutoLabelsLabelGroupsLabelGroupIdLabelDatasAutoLabelsPostResponse = S.Struct({
  "errors": S.Array(S.Tuple(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.String)),
  "success": S.Array(S.Tuple(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))))
}).annotations({ description: 'Return message for CreateLabelDataByAutoLabel.\n\nAttributes:\n    success: List of tuples of (chapter_id, chapter_content_id) for successful inserts.\n    errors: List of tuples of (chapter_id, chapter_content_id, error message) for failed inserts.' })

/**
 * Retrieves all languages in the database.
 *
 * Args:
 *     db: Database session.
 * @summary Read All Languages
 */
export const ReadAllLanguagesLanguagesGetResponseItem = S.Struct({
  "languageCode": S.String,
  "languageName": S.String
}).annotations({ description: 'Pydantic schema for language.\n\nAttributes:\n    language_code: String code key to language.\n    language_name: String name of language.' })
export const ReadAllLanguagesLanguagesGetResponse = S.Array(ReadAllLanguagesLanguagesGetResponseItem)

/**
 * Retrieves a language by its code.
 *
 * Args:
 *     language_code: The code of the language to retrieve.
 *     db: Database session.
 * @summary Read Language By Code
 */
export const ReadLanguageByCodeLanguagesLanguageCodeGetParams = S.Struct({
  "languageCode": S.String
})

export const ReadLanguageByCodeLanguagesLanguageCodeGetResponse = S.Struct({
  "languageCode": S.String,
  "languageName": S.String
}).annotations({ description: 'Pydantic schema for language.\n\nAttributes:\n    language_code: String code key to language.\n    language_name: String name of language.' })

/**
 * Endpoint for retrieving novels in bulk.
 * @summary Read Novels
 */
export const ReadNovelsNovelsGetQueryParams = S.Struct({
  "titleContains": S.optional(S.Union(S.String, S.Null))
})

export const ReadNovelsNovelsGetResponseItem = S.Struct({
  "languageCode": S.String,
  "novelAuthor": S.optional(S.Union(S.String, S.Null)),
  "novelDescription": S.optional(S.Union(S.String, S.Null)),
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "novelTitle": S.String,
  "novelType": S.Literal('original', 'translation', 'other'),
  "novelVisibility": S.Union(S.Literal(0), S.Literal(1), S.Literal(2), S.Literal(3)),
  "sourceWorkId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for novel.\n\nAttributes:\n    novel_id: UUID id of novel in db.\n    novel_title: String title of novel.\n    novel_description: String summary or description of novel.\n    novel_author: String author or description of novel.\n    novel_visibility: Visibility enum of novel.\n    novel_type: NovelType enum of novel.\n    language_code: String code key to language of the novel.\n    source_work_id: UUID foreign key to source work of the novel.' })
export const ReadNovelsNovelsGetResponse = S.Array(ReadNovelsNovelsGetResponseItem)

/**
 * Add a new novel to the database.
 *
 * Raises:
 *     404: Language code or source work not found.
 *     400: Data in some field is too long.
 * @summary Create Novel
 */
export const CreateNovelNovelsPostBody = S.Struct({
  "languageCode": S.String,
  "novelAuthor": S.optional(S.Union(S.String, S.Null)),
  "novelDescription": S.optional(S.Union(S.String, S.Null)),
  "novelTitle": S.String,
  "novelType": S.Literal('original', 'translation', 'other'),
  "novelVisibility": S.Union(S.Literal(0), S.Literal(1), S.Literal(2), S.Literal(3)),
  "sourceWorkId": S.optional(S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null))
}).annotations({ description: 'Pydantic schema to validate forms for creating a novel.\n\nAttributes:\n    novel_title: Novel title to create.\n    novel_description: Description of novel we are creating.\n    novel_author: Author of novel we are creating.\n    novel_visibility: Visibility level of novel we are creating.\n    novel_type: Type of novel we are creating.\n    language_code: String code key to language of novel we are creating.\n    source_work_id: Optional source work to attach to. If None, a new source work is auto-created.' })

export const CreateNovelNovelsPostResponse = S.Struct({
  "languageCode": S.String,
  "novelAuthor": S.optional(S.Union(S.String, S.Null)),
  "novelDescription": S.optional(S.Union(S.String, S.Null)),
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "novelTitle": S.String,
  "novelType": S.Literal('original', 'translation', 'other'),
  "novelVisibility": S.Union(S.Literal(0), S.Literal(1), S.Literal(2), S.Literal(3)),
  "sourceWorkId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for novel.\n\nAttributes:\n    novel_id: UUID id of novel in db.\n    novel_title: String title of novel.\n    novel_description: String summary or description of novel.\n    novel_author: String author or description of novel.\n    novel_visibility: Visibility enum of novel.\n    novel_type: NovelType enum of novel.\n    language_code: String code key to language of the novel.\n    source_work_id: UUID foreign key to source work of the novel.' })

/**
 * Endpoint for retrieving novels that the user has special access to.
 * @summary Read Novels Mine
 */
export const readNovelsMineNovelsMineGetQueryEditableDefault = false;

export const ReadNovelsMineNovelsMineGetQueryParams = S.Struct({
  "editable": S.optionalWith(S.Boolean, { default: () => readNovelsMineNovelsMineGetQueryEditableDefault }),
  "titleContains": S.optional(S.Union(S.String, S.Null))
})

export const ReadNovelsMineNovelsMineGetResponseItem = S.Struct({
  "languageCode": S.String,
  "novelAuthor": S.optional(S.Union(S.String, S.Null)),
  "novelDescription": S.optional(S.Union(S.String, S.Null)),
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "novelTitle": S.String,
  "novelType": S.Literal('original', 'translation', 'other'),
  "novelVisibility": S.Union(S.Literal(0), S.Literal(1), S.Literal(2), S.Literal(3)),
  "sourceWorkId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for novel.\n\nAttributes:\n    novel_id: UUID id of novel in db.\n    novel_title: String title of novel.\n    novel_description: String summary or description of novel.\n    novel_author: String author or description of novel.\n    novel_visibility: Visibility enum of novel.\n    novel_type: NovelType enum of novel.\n    language_code: String code key to language of the novel.\n    source_work_id: UUID foreign key to source work of the novel.' })
export const ReadNovelsMineNovelsMineGetResponse = S.Array(ReadNovelsMineNovelsMineGetResponseItem)

/**
 * Endpoint for retrieving a novel by id.
 *
 * Raises:
 *     404: Novel not found (or insufficient permissions).
 * @summary Read Novel
 */
export const ReadNovelNovelsNovelIdGetParams = S.Struct({
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const ReadNovelNovelsNovelIdGetResponse = S.Struct({
  "languageCode": S.String,
  "novelAuthor": S.optional(S.Union(S.String, S.Null)),
  "novelDescription": S.optional(S.Union(S.String, S.Null)),
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "novelTitle": S.String,
  "novelType": S.Literal('original', 'translation', 'other'),
  "novelVisibility": S.Union(S.Literal(0), S.Literal(1), S.Literal(2), S.Literal(3)),
  "sourceWorkId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for novel.\n\nAttributes:\n    novel_id: UUID id of novel in db.\n    novel_title: String title of novel.\n    novel_description: String summary or description of novel.\n    novel_author: String author or description of novel.\n    novel_visibility: Visibility enum of novel.\n    novel_type: NovelType enum of novel.\n    language_code: String code key to language of the novel.\n    source_work_id: UUID foreign key to source work of the novel.' })

/**
 * Update the novel with novel_id.
 *
 * Raises:
 *     404: Novel not found.
 *     401: Insufficient permissions (user is not owner/editor).
 *     400: Data in some field exceeds maximum length.
 * @summary Update Novel
 */
export const UpdateNovelNovelsNovelIdPatchParams = S.Struct({
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const UpdateNovelNovelsNovelIdPatchBody = S.Struct({
  "novelAuthor": S.optional(S.Union(S.String, S.Null)),
  "novelDescription": S.optional(S.Union(S.String, S.Null)),
  "novelTitle": S.optional(S.Union(S.String, S.Null)),
  "novelType": S.optional(S.Union(S.Literal('original', 'translation', 'other'), S.Null)),
  "novelVisibility": S.optional(S.Union(S.Union(S.Literal(0), S.Literal(1), S.Literal(2), S.Literal(3)), S.Null))
}).annotations({ description: 'Pydantic schema to validate forms for updating a novel. The novel id will be passed into the router endpoint.\n\nAttributes:\n    novel_title: Updated title to novel we are updating. If None, then do not update.\n    novel_description: Updated description of novel we are updating. If None, then do not update.\n    novel_author: Author of novel we are creating. If None, then do not update.\n    novel_visibility: Updated visibility level of novel we are updating. If None, then do not update.\n    novel_type: Updated novel type. If None, then do not update.' })

export const UpdateNovelNovelsNovelIdPatchResponse = S.Struct({
  "languageCode": S.String,
  "novelAuthor": S.optional(S.Union(S.String, S.Null)),
  "novelDescription": S.optional(S.Union(S.String, S.Null)),
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "novelTitle": S.String,
  "novelType": S.Literal('original', 'translation', 'other'),
  "novelVisibility": S.Union(S.Literal(0), S.Literal(1), S.Literal(2), S.Literal(3)),
  "sourceWorkId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for novel.\n\nAttributes:\n    novel_id: UUID id of novel in db.\n    novel_title: String title of novel.\n    novel_description: String summary or description of novel.\n    novel_author: String author or description of novel.\n    novel_visibility: Visibility enum of novel.\n    novel_type: NovelType enum of novel.\n    language_code: String code key to language of the novel.\n    source_work_id: UUID foreign key to source work of the novel.' })

/**
 * Insert a new chapter into the database. Returns chapter metadata and initial empty content.
 *
 * Raises:
 *     404: Novel not found.
 *     409: Chapter with this chapter number already exists in this novel.
 *     401: Insufficient permissions.
 * @summary Create Chapter
 */
export const CreateChapterNovelsNovelIdChaptersPostParams = S.Struct({
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const createChapterNovelsNovelIdChaptersPostBodyChapterIsPublicDefault = false;
export const createChapterNovelsNovelIdChaptersPostBodyChapterTitleDefault = ``;

export const CreateChapterNovelsNovelIdChaptersPostBody = S.Struct({
  "chapterIsPublic": S.optionalWith(S.Boolean, { default: () => createChapterNovelsNovelIdChaptersPostBodyChapterIsPublicDefault }),
  "chapterNum": S.Number,
  "chapterTitle": S.optionalWith(S.String, { default: () => createChapterNovelsNovelIdChaptersPostBodyChapterTitleDefault })
}).annotations({ description: 'Pydantic schema to validate data for creating a new chapter. The novel_id is expected to be passed via the URL path.\n\nAttributes:\n    chapter_num: The chapter number to create.\n    chapter_title: Title of the chapter. Defaults to empty string.\n    chapter_is_public: Whether the chapter is publicly visible. Defaults to False.' })

export const CreateChapterNovelsNovelIdChaptersPostResponse = S.Struct({
  "content": S.Struct({
  "chapterContentId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "chapterContentText": S.String,
  "chapterContentVersion": S.Number
}).annotations({ description: 'Pydantic schema for the text content of a chapter.\n\nAttributes:\n    chapter_content_text: The full text content of the chapter.\n    chapter_content_version: The version number of the text content, used for optimistic concurrency control when updating text.\n    chapter_content_id: The UUID of the text content, used for optimistic concurrency control when updating text.' }),
  "metadata": S.Struct({
  "chapterId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "chapterIsPublic": S.Boolean,
  "chapterNum": S.Number,
  "chapterTitle": S.String,
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for chapter metadata. Represents a single \"chapter\" entry, which groups all its revisions.\n\nAttributes:\n    chapter_id: UUID primary key identifier.\n    chapter_num: The chapter number.\n    novel_id: UUID foreign key to the novel this chapter belongs to.' })
}).annotations({ description: 'Pydantic schema for aggregating a ChapterContent and a Chapter together.\n\nAttributes:\n    metadata: The metadata of the chapter, such as title and whether it\'s primary.\n    content: The text content of the chapter.' })

/**
 * Endpoint for registering a new user. Client with registration request must not be logged in.
 *
 * Args:
 *     request: Create user request.
 *     db: Database dependency.
 *     current_user: Optional user dependency. Should be None for this function to succeed.
 * @summary Register User
 */
export const RegisterUserRegisterPostBody = S.Struct({
  "userName": S.String,
  "userPassword": S.String,
  "userType": S.Literal('user', 'admin').annotations({ description: 'Enum of possible user types.' })
}).annotations({ description: 'Pydantic schema to validate data required to create a user.\n\nAttributes:\n    user_name: Username of user being created.\n    user_password: Unhashed password of user being create.\n    user_type: UserType type of user to be created.\nNotes:' })

export const RegisterUserRegisterPostResponse = S.Struct({
  "userId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "userName": S.String,
  "userType": S.Literal('user', 'admin').annotations({ description: 'Enum of possible user types.' })
}).annotations({ description: 'Pydantic model for user information.\n\nAttributes:\n    user_id: id of this user.\n    user_name: Username for this user.\n    user_type: A value in UserType (e.g. \'admin\', or \'user\')' })

/**
 * Endpoint for retrieving source works in bulk, optionally filtered by title substring.
 * @summary Read Source Works
 */
export const readSourceWorksSourceWorksGetQueryRetNovelsDefault = false;

export const ReadSourceWorksSourceWorksGetQueryParams = S.Struct({
  "titleContains": S.optional(S.Union(S.String, S.Null)),
  "retNovels": S.optionalWith(S.Boolean, { default: () => readSourceWorksSourceWorksGetQueryRetNovelsDefault })
})

export const ReadSourceWorksSourceWorksGetResponseItem = S.Struct({
  "novels": S.Array(S.Struct({
  "languageCode": S.String,
  "novelAuthor": S.optional(S.Union(S.String, S.Null)),
  "novelDescription": S.optional(S.Union(S.String, S.Null)),
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "novelTitle": S.String,
  "novelType": S.Literal('original', 'translation', 'other'),
  "novelVisibility": S.Union(S.Literal(0), S.Literal(1), S.Literal(2), S.Literal(3)),
  "sourceWorkId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for novel.\n\nAttributes:\n    novel_id: UUID id of novel in db.\n    novel_title: String title of novel.\n    novel_description: String summary or description of novel.\n    novel_author: String author or description of novel.\n    novel_visibility: Visibility enum of novel.\n    novel_type: NovelType enum of novel.\n    language_code: String code key to language of the novel.\n    source_work_id: UUID foreign key to source work of the novel.' })),
  "sourceWork": S.Struct({
  "sourceWorkDescription": S.optional(S.Union(S.String, S.Null)),
  "sourceWorkId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "sourceWorkTitle": S.String
}).annotations({ description: 'Pydantic schema for a source work.\n\nAttributes:\n    source_work_id: UUID id of source work in db.\n    source_work_title: Title of the source work.\n    source_work_description: Optional description of the source work.' })
}).annotations({ description: 'Pydantic schema to represent a source work and all its associated novels.\n\nAttributes:\n    source_work: The source work metadata.\n    novels: A list of novels associated with this source work.' })
export const ReadSourceWorksSourceWorksGetResponse = S.Array(ReadSourceWorksSourceWorksGetResponseItem)

/**
 * Create a new source work.
 *
 * Raises:
 *     400: Data in some field is too long.
 * @summary Create Source Work
 */
export const CreateSourceWorkSourceWorksPostBody = S.Struct({
  "sourceWorkDescription": S.optional(S.Union(S.String, S.Null)),
  "sourceWorkTitle": S.String
}).annotations({ description: 'Pydantic schema to validate forms for creating a source work.\n\nAttributes:\n    source_work_title: Title of the source work to create.\n    source_work_description: Optional description.' })

export const CreateSourceWorkSourceWorksPostResponse = S.Struct({
  "sourceWorkDescription": S.optional(S.Union(S.String, S.Null)),
  "sourceWorkId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "sourceWorkTitle": S.String
}).annotations({ description: 'Pydantic schema for a source work.\n\nAttributes:\n    source_work_id: UUID id of source work in db.\n    source_work_title: Title of the source work.\n    source_work_description: Optional description of the source work.' })

/**
 * Endpoint for retrieving a source work by id.
 *
 * Raises:
 *     404: Source work not found (or insufficient permissions).
 * @summary Read Source Work
 */
export const ReadSourceWorkSourceWorksSourceWorkIdGetParams = S.Struct({
  "sourceWorkId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const ReadSourceWorkSourceWorksSourceWorkIdGetResponse = S.Struct({
  "sourceWorkDescription": S.optional(S.Union(S.String, S.Null)),
  "sourceWorkId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "sourceWorkTitle": S.String
}).annotations({ description: 'Pydantic schema for a source work.\n\nAttributes:\n    source_work_id: UUID id of source work in db.\n    source_work_title: Title of the source work.\n    source_work_description: Optional description of the source work.' })

/**
 * Update a source work's metadata.
 *
 * Raises:
 *     404: Source work not found.
 *     401: Insufficient permissions.
 *     400: Data in some field exceeds maximum length.
 * @summary Update Source Work
 */
export const UpdateSourceWorkSourceWorksSourceWorkIdPatchParams = S.Struct({
  "sourceWorkId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const UpdateSourceWorkSourceWorksSourceWorkIdPatchBody = S.Struct({
  "sourceWorkDescription": S.optional(S.Union(S.String, S.Null)),
  "sourceWorkTitle": S.optional(S.Union(S.String, S.Null))
}).annotations({ description: 'Pydantic schema to validate forms for updating a source work.\n\nAttributes:\n    source_work_title: Updated title. If None, do not update.\n    source_work_description: Updated description. If None, do not update.' })

export const UpdateSourceWorkSourceWorksSourceWorkIdPatchResponse = S.Struct({
  "sourceWorkDescription": S.optional(S.Union(S.String, S.Null)),
  "sourceWorkId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "sourceWorkTitle": S.String
}).annotations({ description: 'Pydantic schema for a source work.\n\nAttributes:\n    source_work_id: UUID id of source work in db.\n    source_work_title: Title of the source work.\n    source_work_description: Optional description of the source work.' })

/**
 * Endpoint for retrieving novels belonging to a source work.
 *
 * Raises:
 *     404: Source work not found (or insufficient permissions).
 * @summary Read Novels By Source Work
 */
export const ReadNovelsBySourceWorkSourceWorksSourceWorkIdNovelsGetParams = S.Struct({
  "sourceWorkId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const ReadNovelsBySourceWorkSourceWorksSourceWorkIdNovelsGetResponseItem = S.Struct({
  "languageCode": S.String,
  "novelAuthor": S.optional(S.Union(S.String, S.Null)),
  "novelDescription": S.optional(S.Union(S.String, S.Null)),
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "novelTitle": S.String,
  "novelType": S.Literal('original', 'translation', 'other'),
  "novelVisibility": S.Union(S.Literal(0), S.Literal(1), S.Literal(2), S.Literal(3)),
  "sourceWorkId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}).annotations({ description: 'Pydantic schema for novel.\n\nAttributes:\n    novel_id: UUID id of novel in db.\n    novel_title: String title of novel.\n    novel_description: String summary or description of novel.\n    novel_author: String author or description of novel.\n    novel_visibility: Visibility enum of novel.\n    novel_type: NovelType enum of novel.\n    language_code: String code key to language of the novel.\n    source_work_id: UUID foreign key to source work of the novel.' })
export const ReadNovelsBySourceWorkSourceWorksSourceWorkIdNovelsGetResponse = S.Array(ReadNovelsBySourceWorkSourceWorksSourceWorkIdNovelsGetResponseItem)

/**
 * Verifies a client's login request and returns a token if it succeeds.
 *
 * Args:
 *     db: Database dependency.
 *     form_data: OAuth2PasswordRequestForm dependency.
 * @summary Login For Access Token
 */
export const LoginForAccessTokenTokenPostResponse = S.Struct({
  "access_token": S.String,
  "token_type": S.String
}).annotations({ description: 'Pydantic schema for a JWT\n\nAttributes:\n    access_token: Payload.\n    token_type: Type of token.' })

/**
 * Creates a user with metadata request, provided that the current_user has sufficient permissions.
 *
 * Args:
 *     db: Database dependency.
 *     current_user: Current user dependency. Must not be None (e.g. user must be logged in).
 *     request: Metadata of user to be added.
 * @summary Create User
 */
export const CreateUserUsersPostBody = S.Struct({
  "userName": S.String,
  "userPassword": S.String,
  "userType": S.Literal('user', 'admin').annotations({ description: 'Enum of possible user types.' })
}).annotations({ description: 'Pydantic schema to validate data required to create a user.\n\nAttributes:\n    user_name: Username of user being created.\n    user_password: Unhashed password of user being create.\n    user_type: UserType type of user to be created.\nNotes:' })

export const CreateUserUsersPostResponse = S.Struct({
  "userId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "userName": S.String,
  "userType": S.Literal('user', 'admin').annotations({ description: 'Enum of possible user types.' })
}).annotations({ description: 'Pydantic model for user information.\n\nAttributes:\n    user_id: id of this user.\n    user_name: Username for this user.\n    user_type: A value in UserType (e.g. \'admin\', or \'user\')' })

/**
 * Delete the user currently logged in.
 * @summary Delete User Me
 */
export const DeleteUserMeUsersMeDeleteResponse = S.Struct({
  "detail": S.optional(S.Union(S.String, S.Null)),
  "status": S.Literal('success', 'fail', 'verify')
}).annotations({ description: 'Pydantic schema to return status after deleting a user\n\nAttributes:\n    status: One of \'success\', \'fail\', \'verify\'.\n    detail: String denoting details of operation.' })

/**
 * Return the current logged in user.
 *
 * Args:
 *     current_user: Current user dependency.
 * @summary Read User Me
 */
export const ReadUserMeUsersMeGetResponse = S.Struct({
  "userId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "userName": S.String,
  "userType": S.Literal('user', 'admin').annotations({ description: 'Enum of possible user types.' })
}).annotations({ description: 'Pydantic model for user information.\n\nAttributes:\n    user_id: id of this user.\n    user_name: Username for this user.\n    user_type: A value in UserType (e.g. \'admin\', or \'user\')' })

/**
 * Delete the user with user_id if the current user has sufficient permissions to perform this action. Throw an exception if the user currently logged in has insufficient permissions.
 * @summary Delete User
 */
export const DeleteUserUsersUserIdDeleteParams = S.Struct({
  "userId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const DeleteUserUsersUserIdDeleteResponse = S.Struct({
  "detail": S.optional(S.Union(S.String, S.Null)),
  "status": S.Literal('success', 'fail', 'verify')
}).annotations({ description: 'Pydantic schema to return status after deleting a user\n\nAttributes:\n    status: One of \'success\', \'fail\', \'verify\'.\n    detail: String denoting details of operation.' })

/**
 * Get user by username.
 *
 * Args:
 *     user_name: Username of user.
 *     db: Database dependency.
 * @summary Read User
 */
export const ReadUserUsersUserNameGetParams = S.Struct({
  "userName": S.String
})

export const ReadUserUsersUserNameGetResponse = S.Struct({
  "userId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "userName": S.String,
  "userType": S.Literal('user', 'admin').annotations({ description: 'Enum of possible user types.' })
}).annotations({ description: 'Pydantic model for user information.\n\nAttributes:\n    user_id: id of this user.\n    user_name: Username for this user.\n    user_type: A value in UserType (e.g. \'admin\', or \'user\')' })

